server:
  port: 8083

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri:
          lb://CUSTOMER-SERVICE
        predicates:
        - Path=/citizen/**